/*©agpl*************************************************************************
*                                                                              *
* This file is part of FRIEND UNIFYING PLATFORM.                               *
*                                                                              *
* This program is free software: you can redistribute it and/or modify         *
* it under the terms of the GNU Affero General Public License as published by  *
* the Free Software Foundation, either version 3 of the License, or            *
* (at your option) any later version.                                          *
*                                                                              *
* This program is distributed in the hope that it will be useful,              *
* but WITHOUT ANY WARRANTY; without even the implied warranty of               *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 *
* GNU Affero General Public License for more details.                          *
*                                                                              *
* You should have received a copy of the GNU Affero General Public License     *
* along with this program.  If not, see <http://www.gnu.org/licenses/>.        *
*                                                                              *
*****************************************************************************©*/

// Do not edit this file!
var server = {
	mysql : {
		host : 'presence_database_host',		// Example 'localhost' or 'mydomain.com'
		port : 3306,							// Example: 3206
		user : 'presence_database_user',		// Example: 'alfred'
		pass : 'presence_database_password',	// Example: 'alfred_password'
		name : 'presence_database_name',		// Example: 'presence'
	},
	tls : {
		keyPath : 'path_to_key.pem',		// Example: '/opt/friendup/cfg/crt/key.pem'
		certPath : 'path_to_cert.pem',		// Example: '/opt/friendup/cfg/crt/cert.pem'
		key : null,
		cert : null,
	},
	// failure to provide this means invites wont work
	domain : 'presence_domain',				// Example: 'localhost' or 'mydomain.com'
	tcp : {
		port  : 27960,
		proxy : null,
	},
	ws : {
		port : 27970,
		proxy : null,
		// proxy : '/presence/guest/',
	},
	friendcore : {
		host  : 'friendcore_domain',		// Example: 'localhost' or 'mydomain.com'
		port  : 6502,
	},
	account : {
		settings : {
		},
	},
	room : {
		settings : {
		},
	},
};

var shared = {
	rtc : {
		iceServers : [
			{
				urls : [
					"stun:stun_url.com:3478",	// Example: 'stun:mystunserver.com:3478'
				],
			},
			{
				urls : [
					"turn:turn_url.com:3478",	// Example: 'turn:myturnseerver.com:3478'
				],
				username : 'turn_username',		// Example: 'alfred'
				credential : 'turn_password',	// Example: 'alfred_password'
			},
		],
	},
};

var conf = {
	shared : shared,
	server : server,
};

module.exports = conf;
