/*©agpl*************************************************************************
*                                                                              *
* Friend Unifying Platform                                                     *
* ------------------------                                                     *
*                                                                              *
* Copyright 2014-2016 Friend Software Labs AS, all rights reserved.            *
* Hillevaagsveien 14, 4016 Stavanger, Norway                                   *
* Tel.: (+47) 40 72 96 56                                                      *
* Mail: info@friendos.com                                                      *
*                                                                              *
*****************************************************************************©*/

// Do not edit this file!
var server = {
	mysql : {
		host : 'presence_database_host',		// Example 'localhost' or 'mydomain.com'
		port : 3206,							// Example: 3206
		user : 'presence_database_user',		// Example: 'alfred'
		pass : 'presence_database_password',	// Example: 'alfred_password'
		name : 'presence_database_name',		// Example: 'presence'
	},
	tls : {
		keyPath : 'path_to_key.pem',		// Example: '/opt/friendup/cfg/crt/key.pem'
		certPath : 'path_to_cert.pem',		// Example: '/opt/friendup/cfg/crt/cert.pem'
		key : null,
		cert : null,
	},
	// failure to provide this means invites wont work
	domain : 'presence_domain',				// Example: 'localhost' or 'mydomain.com'
	tcp : {
		port  : 27960,
		proxy : null,
	},
	ws : {
		port : 27970,
		proxy : null,
		// proxy : '/presence/guest/',
	},
	friendcore : {
		host  : 'friendcore_domain',		// Example: 'localhost' or 'mydomain.com'
		port  : 6502,
	},
	account : {
		settings : {
		},
	},
	room : {
		settings : {
		},
	},
};

var shared = {
	rtc : {
		iceServers : [
			{
				urls : [
					"stun:stun_url.com:3478",	// Example: 'stun:mystunserver.com:3478'
				],
			},
			{
				urls : [
					"turn:turn_url.com:3478",	// Example: 'turn:myturnseerver.com:3478'
				],
				username : 'turn_username',		// Example: 'alfred'
				credential : 'turn_password',	// Example: 'alfred_password'
			},
		],
	},
};

var conf = {
	shared : shared,
	server : server,
};

module.exports = conf;
